### ISSUE TITLE
Mutabilità dei Node

### ISSUE THREAD

**Issue by EvaristeGalois11** [scari08/QuoridorGame#1]
Quando muovi un player aggiorni i campi r e c del Node (con un meccanismo che non mi va di capire), ciò ti porterà notevoli problemi con il calcolo del percorso. Cambiare le coordinate non cambia ad esempio la lista dei vicini, e ti ritroverai con un paradossale nodo vicino a se stesso che però non è più lui ma anche sì. Per sicurezza dichiara i campi r e c final ed adegua il codice alla loro immutabilità.
Devi cambiare il puntatore della tua posizione, non il nodo puntato.

**Comment by scari08** [comment]
ALREADY FIXED
